WebFrontend: Restore "main" and "TV/Recordings" pages
Commits 0c1361c and 051a703 added Catagory and Sort parameters to
Dvr/GetRecordedList and weren't added for the WebFrontend calls.

Caused the main and Recordings pages to be blank and log messages:

   ... SyntaxError: too few arguments in call to GetRecordedList()