Fix compilation on windows after 47d67e6722092471069c52d1b0a37509477b5d85.
This commit should fix compilation on windows as it ads back pthread.h in jobqueue.h since without it the following error is thrown:

In file included from ../libmyth/programinfo.h:18:0,
from jobqueue.cpp:19:
../libmythbase/mythdbcon.h:129:17: warning: 'void
MSqlEscapeAsAQuery(QString&, MSqlBindings&)' redeclared without
dllimport attribute: previous dllimport ignored
In file included from jobqueue.cpp:21:0:
../libmythbase/util.h:39:50: warning: 'dllimport' attribute ignored
jobqueue.cpp: In member function 'void JobQueue::StartChildJob(void*
()(void), int)':
jobqueue.cpp:1712:5: error: 'pthread_t' was not declared in this scope
jobqueue.cpp:1712:15: error: expected ';' before 'childThread'
jobqueue.cpp:1713:5: error: 'pthread_attr_t' was not declared in this scope
jobqueue.cpp:1713:20: error: expected ';' before 'attr'
jobqueue.cpp:1714:24: error: 'attr' was not declared in this scope
jobqueue.cpp:1714:28: error: 'pthread_attr_init' was not declared in
this scope
jobqueue.cpp:1715:40: error: 'PTHREAD_CREATE_DETACHED' was not declared
in this scope
jobqueue.cpp:1715:63: error: 'pthread_attr_setdetachstate' was not
declared in this scope
jobqueue.cpp:1716:21: error: 'childThread' was not declared in this scope
jobqueue.cpp:1716:64: error: 'pthread_create' was not declared in this scope
jobqueue.cpp:1717:31: error: 'pthread_attr_destroy' was not declared in
this scope
make[2]: *** [jobqueue.o] Error 1
make[1]: *** [sub-libmythtv-make_default] Error 2
make: *** [libs] Error 2