Remove raise of StopIteration in generator
Tom Peterson's suggested change to replace the
"raise StopIteration" lines with "return" inside the
generator routine has been implemented in ttvdbv4_api.py.
This is the PEP 479-compliant way to end a generator.

In myth4ttvdbv4.py, the buildSingle() routine has
been updated to accommodate a possible StopIteration
exception when the generator is called. If that
exception happens, we will exit with a "No matching
episode found" error message. Similarly, buildCollection()
has been updated to exit with a "No matching collection
found" error message when the provided reference
identifier does not correspond to a known TV series.

The tvmaze metadata grabber had similar vague failures.

For a non-existent episode:
tvmaze.py -l en -a US -D 32938 2 35
ERROR: <class 'AttributeError'> : 'NoneType' object has no attribute 'name'

For a non-existent series:
tvmaze.py -l en -a US -C 99999
ERROR: <class 'AttributeError'> : 'NoneType' object has no attribute 'name'

The tvmaze.py script has been updated to switch these to:

tvmaze.py -l en -a US -D 32938 2 35
ERROR: <class 'SystemExit'> : No matching episode found

tvmaze.py -l en -a US -C 99999
ERROR: <class 'SystemExit'> : No matching collection found

This provides consistent behavior between ttvdb4.py and
tvmaze.py grabbers for these types of failures.

Resolves #1433