Python Bindings: Fix uncaught exception in 'deadlinesocket'
Python Bindings throws an error if the socket does not provide data:
Traceback (most recent call last):
....
File "/usr/lib/python3/dist-packages/MythTV/utility/other.py", line 374, in dlexpect
raise MythError(MythError.CLOSEDSOCKET)
AttributeError: type object 'MythError' has no attribute 'CLOSEDSOCKET'

Solution:
Align the error code to the methods provided by MythError.SOCKET.

Fixes #423