Fix compilation failure on some systems.
    error: conversion from ‘RecStatus::Type’ to ‘QChar’ is ambiguous

RecStatus::Type is an enum based on an int.  There's no need to
convert it to a character string to do a comparison on it.