mytharchive: fix use of reserved keywords for C23
Testing with Fedora rawhide, builds fail with:

    error: cannot use keyword 'false' as enumeration constant
    typedef enum { false = 0, true = 1 }    bool;
                   ^~~~~
    note: 'false' is a keyword with '-std=c23' onwards
    error: expected ';', identifier or '(' before 'bool'
    typedef enum { false = 0, true = 1 }    bool;
                                            ^~~~

(cherry picked from commit bc4476e671f449ef26f19fd6cedda8e98dcc043b)