Cleanup patch, removes the causes of various compiler warnings. Mostly due to unused params and int vs. uint comparisons.
The following compiler warnings are banished:

bio2jack.c: In function `JACK_srate':
bio2jack.c:676: warning: unused parameter `nframes'
bio2jack.c:676: warning: unused parameter `arg'
bio2jack.c: In function `JACK_Write':
bio2jack.c:1203: warning: comparison between signed and unsigned
bio2jack.c: In function `JACK_GetBytesStoredFromDriver':
bio2jack.c:1446: warning: unused variable `now'
bio2jack.c:1447: warning: unused variable `elapsedMS'
bio2jack.c: In function `JACK_GetMaxBufferedBytes':
bio2jack.c:1630: warning: unused parameter `deviceID'
bio2jack.c: In function `JACK_SetMaxBufferedBytes':
bio2jack.c:1641: warning: unused parameter `deviceID'
bio2jack.c: In function `JACK_SetNumOutputChannels':
bio2jack.c:1667: warning: unused parameter `deviceID'
bio2jack.c:1667: warning: unused parameter `channels'
audiooutputarts.cpp: In member function `virtual int
   AudioOutputARTS::GetVolumeChannel(int)':
audiooutputarts.cpp:99: warning: unused parameter `int channel'
audiooutputarts.cpp: In member function `virtual void
   AudioOutputARTS::SetVolumeChannel(int, int)':
audiooutputarts.cpp:104: warning: unused parameter `int channel'
audiooutputarts.cpp:104: warning: unused parameter `int volume'
audiooutputalsa.cpp: In member function `virtual int
   AudioOutputALSA::getSpaceOnSoundcard()':
audiooutputalsa.cpp:258: warning: comparison between signed and unsigned
   integer expressions
dvbdev/ringbuffy.c: In function `ring_write':
dvbdev/ringbuffy.c:62: warning: implicit declaration of function `memcpy'
dvbdev/transform.c: In function `write_ipack':
dvbdev/transform.c:457: warning: unused variable `ai'
dvbdev/transform.c:459: warning: unused variable `diff'
dvbdev/transform.c: In function `instant_repack':
dvbdev/transform.c:648: warning: comparison between signed and unsigned
dvbdev/transform.c:650: warning: comparison between signed and unsigned
dvbdev/transform.c:662: warning: comparison between signed and unsigned
dvbdev/transform.c:671: warning: comparison between signed and unsigned
dvbdev/transform.c: At top level:
dvbdev/transform.c:316: warning: `ac3_channels' defined but not used
dvbdev/transform.c:317: warning: `ac3_audio_coding' defined but not used


git-svn-id: http://svn.mythtv.org/svn/trunk@5845 7dbf422c-18fa-0310-86e9-fd20926502f2