Catch an AttributeError exception
When running a test scenario with the TV show "Bulletproof", the program was crashing due to an AttributeError. It turns out that the TvMaze database has no 'country' field for that show.

show_country = show_network.get('country')
AttributeError: 'NoneType' object has no attribute 'get'
Exit 1

The enclosing try: ... except block has been updated to collect AttributeError in addition to ValueError.