Update dvbci.cpp
build: Fix build under FreeBSD 13.0

Error was:
recorders/dvbdev/dvbci.cpp:265:38: error: implicit instantiation of undefined template 'std::__1::array<unsigned char, 2048>'
  std::array<uint8_t,MAX_TPDU_SIZE>  m_data {0};

(cherry picked from commit f5a8970de4bce751b291b90856ddaccf4233e2e1)