cmake: test availability of -fcf-protection
Builds on an Orange Pi running Ubuntu 22.04 fail if -fcf-protection
is used.  Compilers are 11.4.0. Architecture is aarch64.

c++, g++ and gcc return: cc1plus:

    error: ‘-fcf-protection=full’ is not supported for this target