Python Bindings: Add compatibility to MariaDB 10.6
MariaDB 10.6 introduced a new keyword 'offset' which collides with
the field 'offset' from the recordedseek table.

Solution:
Backtick all queries related to to this table (in class DBDataRef
and its descendants) to fix this collision.
Note: The Python Bindings use the field names of a SQL table as
properties, therefore simple back-ticking 'offset' won't work.

The related MySQL error is:

MythTV.exceptions.MythDBError: MySQL error 1064:
You have an error in your SQL syntax;
check the manual that corresponds to your MariaDB server version
for the right syntax to use near 'offset,type FROM recordedseek WHERE ...

Tested with python3.6 and python3.10 .