TV grabber ttvdb.py fails with newer versions of
python package request-cache.

This was reported on the forum, it throws this
Error: (module 'requests_cache' has no attribute 'core')

It turned out, that the monkey patch provided by
`mythtv/bindings/python/MythTV/ttvdb/requests_cache_compatability.py`
is only valid for versions of request-cache < '0.5.0'. Newer versions
do not need this patch and versions beyond '0.8.0' crashes with above
error message.
Note: The module requests_cache.core was removed in version '0.8.0'
on Sept. 2021 and deprecated in version '0.6.0' in April, 2021.

Refs #408

(cherry picked from commit da3f00653588813fc225eafa146d975b26986819)