Provide the cache clean action the permission it needs
The github workflow to clean up PR caches failed with:
  Error: Resource not accessible by integration

The issue is that the gh-actions-cleanup requires the
permission to delete caches, per:
https://github.com/actions/gh-actions-cache/issues/85