Remove VERBOSE, put in a forced error message
Now if you try to use VERBOSE instead of LOG, you will get a compile-time
error  message like:

mythlogging.cpp: In function ‘QString logStrerror(int)’:
mythlogging.cpp:1163: error: call to ‘VERBOSE’ declared with attribute error: VERBOSE is gone, use LOG

The conversion is complete.  Next step is to sweep through all the changes
looking for LOC that shouldn't have been removed, and obvious boneheaded
mismappings.